/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.77
 * Generated at: 2022-03-24 10:09:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\"\n");
      out.write("    crossorigin=\"anonymous\">\n");
      out.write("  <link id=\"theme\" rel=\"stylesheet\" href=\"css/style2.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/chat.css\">\n");
      out.write("  <title>chat</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("  <div class=\"container mt-5\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"col-12 text-center\">\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-12\">\n");
      out.write("        <div id=\"wrap-chat\">\n");
      out.write("          <div class=\"card chat-body\">\n");
      out.write("            <div class=\"row mod-row-right\">\n");
      out.write("              <div class=\"col-md-4 contact dark\">\n");
      out.write("                <!-- list user -->\n");
      out.write("                <div class=\"list-contact\">\n");
      out.write("                  <div id=\"search\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\n");
      out.write("                    <div class=\"append-btn-search\">\n");
      out.write("                        <i class=\"material-icons\">\n");
      out.write("                            search\n");
      out.write("                        </i>\n");
      out.write("                    </div>\n");
      out.write("                    <i id=\"hide-contact\" class=\"material-icons\">\n");
      out.write("                      close\n");
      out.write("                    </i>\n");
      out.write("                  </div>\n");
      out.write("                  \n");
      out.write("                  <ul class=\"list-unstyled\">\n");
      out.write("\n");
      out.write("                    <li class=\"media p-2\">\n");
      out.write("                      <img class=\"mr-3 avatar online\" src=\"img/1.jpeg\" alt=\"Generic placeholder image\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <h6 class=\"mt-0 mb-1 name-contact\">Yan <span>12/7/18 8:58 AM</span></h6>\n");
      out.write("                        <p>Cras sit amet, in gravida</p>\n");
      out.write("\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"media contact-active p-2\">\n");
      out.write("                      <img class=\"mr-3 avatar online\" src=\"img/2.jpg\" alt=\"Generic placeholder image\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <h6 class=\"mt-0 mb-1 name-contact\">Linda <span>12/7/18 8:58 AM</span></h6>\n");
      out.write("                        <p>Cras sit amet nibh libero, in gravida</p>\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"media p-2\">\n");
      out.write("                      <img class=\"mr-3 avatar offline\" src=\"img/3.png\" alt=\"Generic placeholder image\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <h6 class=\"mt-0 mb-1 name-contact \">Jamal <span>12/7/18 8:58 AM</span></h6>\n");
      out.write("                        <p>Cras sit amet nibh libero, in gravida</p>\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"media p-2\">\n");
      out.write("                      <img class=\"mr-3 avatar online\" src=\"img/4.jpeg\" alt=\"Generic placeholder image\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <h6 class=\"mt-0 mb-1 name-contact\">Cristian <span>12/7/18 8:58 AM</span></h6>\n");
      out.write("                        <p>Sit amet nibh libero, in gravida</p>\n");
      out.write("\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"media p-2 \">\n");
      out.write("                      <img class=\"mr-3 avatar online\" src=\"img/5.jpeg\" alt=\"Generic placeholder image\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <h6 class=\"mt-0 mb-1 name-contact\">Jack <span>12/7/18 8:58 AM</span></h6>\n");
      out.write("                        <p>Cras sit amet nibh libero, in gravida</p>\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"media p-2\">\n");
      out.write("                      <img class=\"mr-3 avatar offline\" src=\"img/6.jpeg\" alt=\"Generic placeholder image\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <h6 class=\"mt-0 mb-1 name-contact\">Angelica <span>12/7/18 8:58 AM</span></h6>\n");
      out.write("                        <p>Cras sit amet, in gravida</p>\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"media p-2\">\n");
      out.write("                      <img class=\"mr-3 avatar offline\" src=\"img/7.jpeg\" alt=\"Generic placeholder image\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <h6 class=\"mt-0 mb-1 name-contact\">Marcia <span>12/7/18 8:58 AM</span></h6>\n");
      out.write("                        <p>Cras sit amet nibh libero,</p>\n");
      out.write("\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("                <!-- list user -->\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-8 col-12 no-pad dark\">\n");
      out.write("                <div id=\"chatbox\" class=\"dark\">\n");
      out.write("                  <div id=\"filter\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                      <div class=\"col text-left\">\n");
      out.write("                        <i id=\"show-contact\" class=\"material-icons\">\n");
      out.write("                          list\n");
      out.write("                        </i>\n");
      out.write("                        \n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"col text-right\">\n");
      out.write("                        <i class=\"material-icons\">\n");
      out.write("                          add_a_photo\n");
      out.write("                        </i>\n");
      out.write("                        <i class=\"material-icons\" id=\"dropmenu-custom\">\n");
      out.write("                            more_vert\n");
      out.write("                        </i>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div id=\"message-container\">\n");
      out.write("                    <!-- Drop menu -->\n");
      out.write("                    <div  id=\"drop-menu\" class=\"card\"> \n");
      out.write("                      <div class=\"card-body text-right\">\n");
      out.write("                        <ul>\n");
      out.write("                          <li id=\"ligth\">\n");
      out.write("                             Light  <span  class=\"badge badge-ligth\">D</span>\n");
      out.write("                          </li>\n");
      out.write("                          <li id=\"dark\">\n");
      out.write("                             Dark  <span  class=\"badge badge-dark\">D</span>\n");
      out.write("                          </li>\n");
      out.write("                          <li id=\"hot\">\n");
      out.write("                              Heat <span  class=\"badge badge-hot\">D</span>\n");
      out.write("                           </li>\n");
      out.write("                        </ul>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- drop menu -->\n");
      out.write("                    <ul>\n");
      out.write("                      <li>\n");
      out.write("                        <div class=\"alert alert-primary me\">\n");
      out.write("                          hello\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"me-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <img class=\"mr-3 avatar other-img\" src=\"img/2.jpg\" alt=\"Generic placeholder image\">\n");
      out.write("                        <div class=\"alert alert-primary other\">\n");
      out.write("                          hey there\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"other-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <div class=\"alert alert-primary me\">\n");
      out.write("                          great are you ok\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"me-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <img class=\"mr-3 avatar other-img\" src=\"img/2.jpg\" alt=\"Generic placeholder image\">\n");
      out.write("                        <div class=\"alert alert-primary other\">\n");
      out.write("                          way!!!\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"other-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <img class=\"mr-3 avatar other-img\" src=\"img/2.jpg\" alt=\"Generic placeholder image\">\n");
      out.write("                        <div class=\"alert alert-primary other\">\n");
      out.write("                          Great is on this Quidem adipisci, aperiam eaque quia\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"other-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <img class=\"mr-3 avatar other-img\" src=\"img/2.jpg\" alt=\"Generic placeholder image\">\n");
      out.write("                        <div class=\"alert alert-primary other\">\n");
      out.write("                          Lorem ipsum dolor sit amet consectetur, adipisicing elit.\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"other-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <div class=\"alert alert-primary me\">\n");
      out.write("                          amet consectetur, adipisicing elit.\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"me-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <div class=\"alert alert-primary me\">\n");
      out.write("                          Lorem ipsum dolor sit amet consectetur, adipisicing elit.\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"me-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <div class=\"alert alert-primary me\">\n");
      out.write("                          great are you ok\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"me-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <div class=\"alert alert-primary me\">\n");
      out.write("                          great are you ok amet consectetur, adipisicing elit.\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"me-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <img class=\"mr-3 avatar other-img\" src=\"img/2.jpg\" alt=\"Generic placeholder image\">\n");
      out.write("                        <div class=\"alert alert-primary other\">\n");
      out.write("                          Lorem ipsum dolor sit ?\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"other-date\">sent on: 9/27/18 10:52 AM</span>\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                  </div>\n");
      out.write("                  <div id=\"input-message\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"Your message\">\n");
      out.write("                    <button class=\"btn btn-primary btn-sm\" type=\"submit\">\n");
      out.write("                        <i class=\"material-icons\">\n");
      out.write("                            near_me\n");
      out.write("                        </i>\n");
      out.write("                    </button>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!--col-md-12-->\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"js/jQuery.js\"></script>\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\"\n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\"\n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("  <script src=\"js/chat.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
