/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.77
 * Generated at: 2022-03-25 08:11:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tutorialCovid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/views/../common/nav.jsp", Long.valueOf(1648195252992L));
    _jspx_dependants.put("/views/../common/footer.jsp", Long.valueOf(1647313776972L));
    _jspx_dependants.put("jar:file:/F:/SWP391/Code/CovidCare_Final/build/web/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1647500883098L));
    _jspx_dependants.put("/views/../common/head.jsp", Long.valueOf(1648109311318L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    ");
 request.setAttribute("title", "HƯỚNG DẪN CHĂM SÓC SỨC KHỎE");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/timetable.css\" />\r\n");
      out.write("    <link rel=\"icon\" href=\"images/icon.png\" type=\"image/icon type\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\" />\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/f0502aaa29.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("    <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("    <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link id=\"theme\" rel=\"stylesheet\" href=\"css/style2.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/chat.css\">\r\n");
      out.write("    \r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <body class=\"body-wrapper\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-light navigation\">\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\".\">\r\n");
      out.write("                        <img src=\"images/icon.png\" alt=\"\" width=\"100\" height=\"100\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("                            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" style=\"display: flex!important;\">\r\n");
      out.write("                        <ul class=\"navbar-nav ml-auto main-nav \">\r\n");
      out.write("                            <li class=\"nav-item active\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\".\">Trang chủ</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul class=\"navbar-nav ml-auto mt-10\">\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fchoose_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--==================================\r\n");
      out.write("        =          Tutorial Covid         =\r\n");
      out.write("        ===================================-->\r\n");
      out.write("\r\n");
      out.write("       <section class=\"dnx_content\">\r\n");
      out.write("    <div class=\"dnx_content_inner\">\r\n");
      out.write("      <div class=\"dnx_content_box\">\r\n");
      out.write("        <h2 class=\"pb-2\">HƯỚNG DẪN CHĂM SÓC SỨC KHỎE</h2>\r\n");
      out.write("        <div class=\"qa\">\r\n");
      out.write("          <div id=\"accordion\">\r\n");
      out.write("            <h5 id=\"qa1\" data-toggle=\"collapse\" data-target=\"#collapse1\" aria-expanded=\"false\" aria-controls=\"collapse1\" class=\"collapsed\">\r\n");
      out.write("              1. Những Điều cần biết khi phát hiện dương tính COVID-19\r\n");
      out.write("            </h5>\r\n");
      out.write("            <div id=\"collapse1\" class=\"collapse\" aria-labelledby=\"qa1\" data-parent=\"#accordion\" style=\"\">\r\n");
      out.write("              <p><strong>✤ Khi nhận được kết quả xét nghiệm dương tính với SARS-COV-2:</strong><br>\r\n");
      out.write("                ♦ Đi thẳng về nhà hoặc nơi lưu trú bằng xe cá nhân, không nên sử dụng các phương tiện giao thông công\r\n");
      out.write("                cộng. Luôn đeo khẩu trang y tế trong suốt quá trình di chuyển và giữ khoảng cách an toàn với người\r\n");
      out.write("                khác.<br>\r\n");
      out.write("                ♦ Khi về đến nhà, chọn nơi tự cách ly phù hợp và bắt đầu cách ly, gọi điện thoại khai báo với Trạm y tế\r\n");
      out.write("                hoặc Tổ Covid cộng đồng hoặc trưởng ấp/khu phố, Tổ dân phố/Tổ nhân dân trên địa bàn cư trú để được hướng\r\n");
      out.write("                dẫn tiếp theo.\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <strong>Những điều cần biết khi người F0 cách ly tại nhà:</strong><br>\r\n");
      out.write("                <strong>✤ Điều kiện để F0 được cách ly, chăm sóc, điều trị tại nhà:</strong><br>\r\n");
      out.write("                Không triệu chứng hoặc triệu chứng mức độ\r\n");
      out.write("                nhẹ (không có suy hô hấp: SpO₂ ≥ 97% khi thở khí trời, nhịp thở ≤ 20 lần/phút) VÀ đã tiêm đủ 2 mũi vắc\r\n");
      out.write("                xin.<br>\r\n");
      out.write("                Lưu ý:<br>\r\n");
      out.write("                ♦ Trường hợp chưa tiêm vắc xin thì độ tuổi từ 3 tháng đến 49 tuổi, không có bệnh nền, không đang mang thai,\r\n");
      out.write("                không béo phì..<br>\r\n");
      out.write("                ♦ Người F0 cách ly tại nhà cần có khả năng tự chăm sóc bản thân. Trường hợp người F0 là trẻ em hoặc\r\n");
      out.write("                người không tự chăm sóc cá nhân được thì cần phải có người hỗ trợ chăm sóc.\r\n");
      out.write("              </p>\r\n");
      out.write("              <div class=\"row\" style=\"padding: 15px 0 0 0;\">\r\n");
      out.write("                <div class=\"col-lg-6 col-md-6 col-sm-6\" style=\"padding: 0 0 0 15px;\">\r\n");
      out.write("                  <p>\r\n");
      out.write("                    <strong>✤ Chuẩn bị vật dụng cần thiết:</strong><br>\r\n");
      out.write("                    ♦ Khẩu trang y tế: ít nhất 2 cái/ngày, đủ dùng trong 2-3 tuần;<br>\r\n");
      out.write("                    ♦ Có bồn nước rửa tay, xà phòng hoặc dung dịch sát khuẩn tay nhanh;<br>\r\n");
      out.write("                    ♦ Dung dịch nước muối sinh lý để súc họng, rửa mũi.<br>\r\n");
      out.write("                    ♦ Vật dụng cá nhân dùng riêng cho người F0;<br>\r\n");
      out.write("                    ♦ Nhiệt kế, thiết bị đo SpO₂, máy đo huyết áp (nếu có);<br>\r\n");
      out.write("                    ♦ Thùng chứa chất thải lây nhiễm có nắp đậy;<br>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 col-md-6 col-sm-6\" style=\"padding: 0 0 0 15px; text-align: center;\">\r\n");
      out.write("                  <img src=\"images/hd1.jpg\" alt=\"\" style=\"max-width: 100%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <p><br>\r\n");
      out.write("                <strong>✤ Thuốc điều trị tại nhà:</strong><br>\r\n");
      out.write("                ♦ Thuốc điều trị COVID-19: do Trạm y tế cấp phát và sử dụng đúng theo hướng dẫn; trường hợp chưa được\r\n");
      out.write("                cấp phát cần liên hệ ngay Trạm y tế.<br>\r\n");
      out.write("                ♦ Thuốc đang điều trị bệnh nền (tăng huyết áp, đái tháo đường, tim mạch, hen phế quản…).<br><br>\r\n");
      out.write("\r\n");
      out.write("                <strong>✤ Những điều người F0 nên làm khi cách ly tại nhà:</strong><br>\r\n");
      out.write("                ♦ Không bi quan, giữ tâm lý luôn thoải mái. Khi gặp khó khăn, liên hệ bác sĩ để được tư vấn từ xa.<br>\r\n");
      out.write("                ♦ Tự theo dõi sức khỏe: đo thân nhiệt, đếm nhịp thở, đo SpO₂ (nếu có) ít nhất hai lần một ngày, hoặc khi\r\n");
      out.write("                cảm thấy mệt, khó thở.<br>\r\n");
      out.write("                ♦ Khai báo hằng ngày trên hệ thống theo dõi sức khỏe F0 tại nhà theo đường\r\n");
      out.write("                link <a href=\"../landingpage\">https://covidcare.com.vn</a>\r\n");
      out.write("                hoặc theo mã QR Code: …<br>\r\n");
      out.write("                ♦ Mang khẩu trang liên tục, rửa tay hoặc sát khuẩn tay thường xuyên.<br>\r\n");
      out.write("                ♦ Rửa mũi, súc họng hàng ngày bằng nước muối sinh lý.<br>\r\n");
      out.write("                ♦ Thường xuyên tập thở, vận động nâng cao sức khỏe.<br>\r\n");
      out.write("                ♦ Uống đủ nước hoặc nhiều hơn nếu có sốt, tiêu chảy. Không bỏ bữa, tăng cường dinh dưỡng, ăn uống đủ\r\n");
      out.write("                chất, tăng cường trái cây tươi, rau xanh.<br>\r\n");
      out.write("                ♦ Nơi cách ly phải thông thoáng, không sử dụng máy lạnh trung tâm; thường xuyên làm vệ sinh các bề mặt,\r\n");
      out.write("                vật dụng, nhà vệ sinh.<br>\r\n");
      out.write("              </p>\r\n");
      out.write("              <div class=\"row\" style=\"padding: 15px 0 0 0;\">\r\n");
      out.write("                <div class=\"col-lg-6 col-md-6 col-sm-6\" style=\"padding: 0 0 0 15px;\">\r\n");
      out.write("                  <p>\r\n");
      out.write("                    <strong>✤ Những điều KHÔNG nên làm:</strong><br>\r\n");
      out.write("                    ♦ KHÔNG tự ý rời khỏi nơi cách ly.<br>\r\n");
      out.write("                    ♦ KHÔNG sử dụng chung vật dụng với người khác.<br>\r\n");
      out.write("                    ♦ KHÔNG ăn uống cùng với người khác.<br>\r\n");
      out.write("                    ♦ KHÔNG tiếp xúc gần với người khác hoặc vật nuôi.<br>\r\n");
      out.write("                    Trường hợp cần có người chăm sóc, người chăm sóc phải đeo khẩu trang,\r\n");
      out.write("                    kính chắn giọt bắn, rửa tay/sát khuẩn tay trước và sau khi chăm sóc.<br>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 col-md-6 col-sm-6\" style=\"padding: 0 0 0 15px; text-align: center\">\r\n");
      out.write("                  <img src=\"images/hd2.jpg\" alt=\"\" style=\"max-width: 100%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <p><br>\r\n");
      out.write("                <strong>✤ Các dấu hiệu cần báo ngay cho y tế địa phương</strong><br>\r\n");
      out.write("                ♦ Khó thở, thở hụt hơi, hoặc ở trẻ em có dấu hiệu thở bất thường: thở rên, rút lõm lồng ngực, phập phồng\r\n");
      out.write("                cánh mũi, khò khè, thở rít thì hít vào.<br>\r\n");
      out.write("                ♦ Nhịp thở tăng: ≥ 21 lần/phút đối với người lớn; ≥ 40 lần/phút đối với trẻ từ 1 đến dưới 5 tuổi; ≥ 30\r\n");
      out.write("                lần/phút đối với trẻ từ 5 đến dưới 12 tuổi.<br>\r\n");
      out.write("                ♦ SpO₂ ≤ 95% (nếu có).<br>\r\n");
      out.write("                ♦ Mạch nhanh &gt; 120 nhịp/phút hoặc dưới 50 lần/phút.<br>\r\n");
      out.write("                ♦ Huyết áp thấp: huyết áp tối đa &lt; 90 mmHg, huyết áp tối thiểu &lt; 60 mmHg (nếu có).<br>\r\n");
      out.write("                ♦ Đau tức ngực thường xuyên, cảm giác bó thắt ngực, đau tăng khi hít sâu.<br>\r\n");
      out.write("                ♦ Thay đổi ý thức: Lú lẫn, ngủ rũ, lơ mơ, rất mệt/mệt lả, trẻ quấy khóc, li bì khó đánh thức, co\r\n");
      out.write("                  giật.<br>\r\n");
      out.write("                  ♦ Tím môi, tím đầu móng tay, móng chân, da xanh, môi nhợt, lạnh đầu ngón tay, ngón chân.<br>\r\n");
      out.write("                  ♦ Không thể uống. Trẻ em bú kém/giảm, ăn kém, nôn.<br>\r\n");
      out.write("                  ♦ Trẻ có biểu hiện: Sốt cao, đỏ mắt, môi đỏ, lưỡi đỏ, ngón tay chân sưng phù nổi ban đỏ, nốt hoặc mảng\r\n");
      out.write("                  xuất huyết...\r\n");
      out.write("              </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h5 id=\"qa2\" class=\"collapsed\" data-toggle=\"collapse\" data-target=\"#collapse2\" aria-expanded=\"false\" aria-controls=\"collapse2\">\r\n");
      out.write("              2. Hướng dẫn xử lý một số triệu chứng thông thường</h5>\r\n");
      out.write("            <div id=\"collapse2\" class=\"collapse\" aria-labelledby=\"qa2\" data-parent=\"#accordion\">\r\n");
      out.write("              <p>\r\n");
      out.write("                <strong>✤ Nếu sốt:</strong><br>\r\n");
      out.write("                ✸ Đối với người lớn: &gt; 38.5 độ hoặc đau đầu, đau người nhiều: uống mỗi lần 1 viên thuốc hạ sốt\r\n");
      out.write("                (paracetamol) 0,5g, có thể lặp lại mỗi 4-6h, ngày không quá 4 viên, uống oresol nếu uống kém/giảm hoặc\r\n");
      out.write("                có thể dùng uống thay nước.<br>\r\n");
      out.write("                ✸ Đối với trẻ em: &gt; 38.50 C, uống thuốc hạ sốt như Paracetamol liều 10 - 15mg/kg/lần, có thể lặp lại mỗi\r\n");
      out.write("                4-6 giờ, ngày không quá 4 lần.<br><br>\r\n");
      out.write("              </p>\r\n");
      out.write("              <table class=\"table table-bordered\">\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><strong>Độ tuổi trẻ em</strong></td>\r\n");
      out.write("                    <td><strong>Dạng thuốc</strong></td>\r\n");
      out.write("                    <td><strong>Liều thuốc tối đa mỗi ngày</strong></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      &lt; 1 tuổi </td>\r\n");
      out.write("                    <td>Paracetamol bột 80mg\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>1 gói x 4 lần/ ngày\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      ( 1 đến dưới 2 tuổi)</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      Paracetamol bột 150mg</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      1 gói x 4 lần/ ngày</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      ( 2 đến dưới 5 tuổi)</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      Paracetamol bột 250mg</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      1 gói x 4 lần / ngày</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      ( 5 đến 12 tuổi)</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      Paracetamol viên 325mg</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      1 viên x 4 lần/ ngày</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      Trên 12 tuổi</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      Paracetamol viên 500mg</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      1 viên x 4 lần/ ngày</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("              <p><br>\r\n");
      out.write("                <strong>✤ Nếu ho: </strong>dùng thuốc giảm ho theo đơn, hoặc các thuốc giảm ho có thành phần thảo dược\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <strong>✤ Căng thẳng tinh thần: </strong><br>\r\n");
      out.write("                <strong>✤ Cách ứng phó với căng thẳng tinh thần</strong><br>\r\n");
      out.write("                ✸ Tránh xem, đọc hoặc nghe những câu chuyện tin tức về dịch COVID-19, nhất là trên các mạng xã hội:\r\n");
      out.write("                zalo, facebook, youtube, tiktok…<br>\r\n");
      out.write("                ✸ Chăm sóc cơ thể và sức khỏe tinh thần của bản thân:<br>\r\n");
      out.write("                ♦ Hít thở sâu hoặc thực hành thiền.<br>\r\n");
      out.write("                ♦ Cố gắng ăn uống lành mạnh, cân bằng dinh dưỡng.<br>\r\n");
      out.write("                ♦ Tập thể dục tại chỗ thường xuyên, vừa sức, không thức khuya.<br>\r\n");
      out.write("                ♦ Tránh sử dụng rượu/bia, thuốc lá, ma túy, các loại thức ăn nước uống có chất kích thích.<br>\r\n");
      out.write("                ✸ Dành thời gian nghỉ ngơi thư giãn. Cố gắng thực hiện một vài hoạt động mà bản thân yêu thích như: đọc\r\n");
      out.write("                sách, vẽ, xem phim, nghe nhạc, làm mô hình, nấu ăn (nếu có thể)…<br>\r\n");
      out.write("                ✸ Tăng cường giao tiếp, kết nối với những người khác. Tâm sự về những lo lắng.<br>\r\n");
      out.write("                ✸ Kết nối với các tổ chức cộng đồng hoặc tôn giáo hoặc nhóm diễn đàn xã hội.<br>\r\n");
      out.write("                ✸ Thừa nhận là việc căng thẳng cũng không sao, không có gì là xấu hổ khi nhờ người khác giúp đỡ.<br>\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h5 id=\"qa3\" class=\"collapsed\" data-toggle=\"collapse\" data-target=\"#collapse3\" aria-expanded=\"false\" aria-controls=\"collapse3\">\r\n");
      out.write("              3. Hướng dẫn tập thở\r\n");
      out.write("            </h5>\r\n");
      out.write("            <div id=\"collapse3\" class=\"collapse\" aria-labelledby=\"qa3\" data-parent=\"#accordion\">\r\n");
      out.write("              <p>\r\n");
      out.write("                Người nhiễm COVID-19 ngoài chăm sóc, dinh dưỡng hợp lý, cần tập luyện tăng cường chức năng hô hấp và vận\r\n");
      out.write("                động hàng ngày với tinh thần lạc quan để cải thiện sức khỏe. Tập luyện, vận động trong giai đoạn này\r\n");
      out.write("                giúp:<br>\r\n");
      out.write("                ✸ Giãn nở lồng ngực, tăng thông khí ra vào phổi, hô hấp tốt hơn.<br>\r\n");
      out.write("                ✸ Tăng thải đờm.<br>\r\n");
      out.write("                ✸ Tăng cường khả năng vận động và các cơ tham gia hô hấp.<br>\r\n");
      out.write("                ✸ Ngăn chặn suy giảm thể chất, cải thiện tinh thần.<br><br>\r\n");
      out.write("                <strong>✤ Một số bài tập thở, vận động gồm:</strong><br>\r\n");
      out.write("                Các bài tập thở\r\n");
      out.write("              </p>\r\n");
      out.write("              <div style=\"padding: 0 0 0 15px; text-align: center\">\r\n");
      out.write("                <img src=\"images/tap_tho1.jpg\" alt=\"\" style=\"max-width: 100%;\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <p>\r\n");
      out.write("                <strong>✤ Bài tập thở giúp giảm khó thở</strong><br>\r\n");
      out.write("                <strong>✤ Bài tập thở mím môi:</strong><br>\r\n");
      out.write("                ✸ Ngồi thẳng lưng hoặc hơi ngả ra sau, thư giãn cổ và vai.<br>\r\n");
      out.write("                ✸ Hít vào chỉ bằng mũi trong 2 giây, như thể đang ngửi một bông hoa.<br>\r\n");
      out.write("                ✸ Thở ra từ từ (trong 4 giây nếu có thể) bằng cách mím môi, như đang thổi nến sinh nhật.<br>\r\n");
      out.write("                ✸ Lặp lại chu kỳ hít vào và thở ra trong 2 phút, vài lần mỗi ngày và khi cần thiết.<br>\r\n");
      out.write("                <strong>✤ Bài tập thở sâu:</strong><br>\r\n");
      out.write("                ✸ Ngả người trên giường hoặc trên ghế sofa với một chiếc gối kê dưới đầu và đầu gối của bạn. Nếu không\r\n");
      out.write("                thể ngả lưng, có thể thực hiện thao tác này khi ngồi thẳng lưng.<br>\r\n");
      out.write("                ✸ Đặt một tay lên bụng, tay kia đặt trên ngực.<br>\r\n");
      out.write("                ✸ Từ từ hít vào bằng mũi; để phổi của bạn được lấp đầy không khí, cho phép bụng của bạn căng lên. (Bàn\r\n");
      out.write("                tay trên bụng nên di chuyển nhiều hơn tay trên ngực.)<br>\r\n");
      out.write("                ✸ Thở ra bằng mũi và khi bạn thở ra, cảm thấy bụng của bạn lõm sâu hơn.<br>\r\n");
      out.write("                ✸ Lặp lại chu kỳ hít vào và thở ra từ 2 đến 5 phút vài lần mỗi ngày và khi cần thiết.<br>\r\n");
      out.write("                TLTK<br>\r\n");
      out.write("                1. American Lung Association. Breathing exercises. Available at: <a href=\"https://www.lung.org/lung-health-diseases/wellness/breathing-exercises\">https://www.lung.org/lung-health-diseases/wellness/breathing-exercises</a><br><br>\r\n");
      out.write("                <strong>✤ Một số tư thế giúp bạn dễ thở hơn</strong><br>\r\n");
      out.write("                Sau đây là một vài tư thế giúp cải thiện tình trạng khó thở của bạn. Hãy nhớ, khi có tình trạng khó thở,\r\n");
      out.write("                liên hệ ngay với trung tâm y tế gần nhất để được hỗ trợ\r\n");
      out.write("              </p>\r\n");
      out.write("              <div style=\"padding: 0 0 0 15px; text-align: center\">\r\n");
      out.write("                <img src=\"images/tap_tho2.jpg\" alt=\"\" style=\"max-width: 100%;\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <p style=\"text-align: center; padding: 10px 0 20px;\">1. Nằm nghiêng 1 bên, kê cao đầu</p>\r\n");
      out.write("              <div style=\"padding: 0 0 0 15px; text-align: center\">\r\n");
      out.write("                <img src=\"images/tap_tho3.jpg\" alt=\"\" style=\"max-width: 100%;\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <p style=\"text-align: center; padding: 10px 0 20px;\">2. Ngồi vào bàn, với cánh tay và gối đặt trên bàn</p>\r\n");
      out.write("\r\n");
      out.write("              <div style=\"padding: 0 0 0 15px; text-align: center\">\r\n");
      out.write("                <img src=\"images/tap_tho4.jpg\" alt=\"\" style=\"max-width: 100%;\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <p style=\"text-align: center; padding: 10px 0 20px;\">3. Ngồi trên ghế, nghiêng người phía trước, đặt tay\r\n");
      out.write("                trên đùi. </p>\r\n");
      out.write("              <div style=\"padding: 0 0 0 15px; text-align: center\">\r\n");
      out.write("                <img src=\"images/tap_tho5.jpg\" alt=\"\" style=\"max-width: 100%;\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <p style=\"text-align: center; padding: 10px 0 20px;\">4. Đứng nghiêng người về phía trước</p>\r\n");
      out.write("              <div style=\"padding: 0 0 0 15px; text-align: center\">\r\n");
      out.write("                <img src=\"images/tap_tho6.jpg\" alt=\"\" style=\"max-width: 100%;\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <p style=\"text-align: center; padding: 10px 0 20px;\">5. Đứng dựa lưng vào tường</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h5 id=\"qa4\" class=\"collapsed\" data-toggle=\"collapse\" data-target=\"#collapse4\" aria-expanded=\"false\" aria-controls=\"collapse4\">\r\n");
      out.write("              4. Dinh dưỡng cho bệnh nhân COVID-19\r\n");
      out.write("            </h5>\r\n");
      out.write("            <div id=\"collapse4\" class=\"collapse\" aria-labelledby=\"qa4\" data-parent=\"#accordion\">\r\n");
      out.write("              <p>\r\n");
      out.write("                <strong>1. Nguyên tắc chung về chế độ dinh dưỡng cho người nhiễm COVID-19 mức độ nhẹ và không có triệu\r\n");
      out.write("                  chứng</strong><br>\r\n");
      out.write("                ♦ Ăn bình thường với đầy đủ và cân đối các nhóm chất dinh dưỡng, đa dạng loại thực phẩm (nếu được) để\r\n");
      out.write("                duy trì thể trạng, thể chất bình thường<br>\r\n");
      out.write("                ♦ Bổ sung thêm 1 đến 2 bữa phụ như sữa và các chế phẩm từ sữa, đặc biệt khi có ăn giảm sút do sốt, ho,\r\n");
      out.write("                mệt mỏi...<br>\r\n");
      out.write("                ♦ Ăn tăng cường nhóm thực phẩm giàu protein (thịt, cá nạc.., đậu đỗ, hạt các loại) để ngăn ngừa teo cơ\r\n");
      out.write("                và tăng sức đề kháng.<br>\r\n");
      out.write("                ♦ Ăn tăng cường trái cây tươi hoặc nước ép trái cây, rau xanh các loại, gia vị (như tỏi, gừng) để tăng\r\n");
      out.write("                cường sức đề kháng.<br>\r\n");
      out.write("                ♦ Uống đủ nước (trung bình 2 lít/ ngày) hoặc nhiều hơn nếu có sốt, tiêu chảy.\r\n");
      out.write("                <br><br>\r\n");
      out.write("\r\n");
      out.write("                <strong>2. Dinh dưỡng đầy đủ và cân đối</strong><br>\r\n");
      out.write("                ♦ Đảm bảo đủ các và đa dạng các nhóm thực phẩm bao gồm: nhóm tinh bột, nhóm sữa và chế phẩm sữa, nhóm\r\n");
      out.write("                dầu mỡ, nhóm rau củ, nhóm thịt cá, nhóm trứng, nhóm các loại hạt, nhóm rau củ màu vàng-xanh thẫm.<br>\r\n");
      out.write("                ♦ Không bỏ bữa: Ăn đủ 3 bữa chính và tăng cường thêm các bữa phụdinh dưỡng<br>\r\n");
      out.write("                ♦ Hạn chế ăn quá nhiều đồ ngọt (khuyến nghị lượng đường &lt; 10% tổng năng lượng ăn vào).<br>\r\n");
      out.write("                  ♦ Không kiêng khem\r\n");
      out.write("                  thực phẩm nếu không có dị ứng thực phẩm hoặc theo lời khuyên riêng của bác sỹ. <br>\r\n");
      out.write("                  ♦ Người có thể trạng\r\n");
      out.write("                  gầy, trẻ em cần bổ sung thêm các thực phẩm có nhiều năng lượng và protein như sữa và các sản phẩm từ\r\n");
      out.write("                  sữa. <br><br>\r\n");
      out.write("\r\n");
      out.write("                  <i>Cụ thể<br>\r\n");
      out.write("                    ♦ Năng lượng 30 - 35 kcal/kg cân nặng/ngày, chất đạm 15-20% tổng năng lượng, nhu cầu chất béo 20-25%\r\n");
      out.write("                    tổng năng lượng, chất đường bột 50 -65% tổng năng lượng.<br>\r\n");
      out.write("                    ♦ Cung cấp đầy đủ vitamin và khoáng chất theo lứa tuổi. Đặc biệt tăng cường các thực phẩm giàu\r\n");
      out.write("                    vitamin\r\n");
      out.write("                    A, C, D, E; các thực phẩm giàu kẽm và selen. Rau xanh 300g/ngày, hoa quả 200g/ngày.<br>\r\n");
      out.write("                    ♦ Chất xơ cung cấp 18-20g/ ngày.<br>\r\n");
      out.write("                    ♦ Muối 5g/ngày.<br>\r\n");
      out.write("                    ♦ Uống nhiều nước (40-45ml/kg cân nặng/ngày), nên uống nước ấm và rải rác trong ngày, tránh tình\r\n");
      out.write("                    trạng\r\n");
      out.write("                    chỉ uống khi thấy khát, nên uống nước lọc, nước ép hoa quả. Người bệnh có sốt nên uống Orezol để bù\r\n");
      out.write("                    nước và điện giải</i><br><br>\r\n");
      out.write("\r\n");
      out.write("                  <strong>3. Dinh dưỡng an toàn</strong><br>\r\n");
      out.write("                  ♦ Tránh đồ ăn, uống có nhiều đường, nhiều muối, rượu, bia.<br>\r\n");
      out.write("                  ♦ Thực phẩm phải bảo đảm an toàn, vệ sinh. Không dùng thực phẩm ôi, thiu, quá hạn sử dụng.<br>\r\n");
      out.write("                  ♦ Bảo đảm vệ sinh khi chế biến thực phẩm. Luôn rửa tay trước và sau khi chế biến thực phẩm.<br>\r\n");
      out.write("                  ♦ Sử dụng các sản phẩm dinh dưỡng bổ sung cần theo hướng dẫn của chuyên gia dinh dưỡng.\r\n");
      out.write("                  <br><br>\r\n");
      out.write("                  <strong>4. Lựa chọn thực phẩm</strong><br><br>\r\n");
      out.write("              </p>\r\n");
      out.write("              <table class=\"table table-bordered\">\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><strong>Thực phẩm nên dùng</strong></td>\r\n");
      out.write("                    <td><strong>Thực phẩm hạn chế dùng</strong></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    \r\n");
      out.write("                    <td>♦ Gạo, mỳ, ngô, khoai, sắn,…<br>\r\n");
      out.write("                      ♦ Các loại hạt: đậu đỗ, vừng, lạc…<br>\r\n");
      out.write("                      ♦ Sữa và các sản phẩm từ sữa: sữa bột, sữa tươi, sữa chua…<br>\r\n");
      out.write("                      ♦ Thịt các loại, cá, tôm…<br>\r\n");
      out.write("                      ♦ Trứng và các sản phẩm từ trứng: trứng gà, trứng vịt, trứng chim cút…<br>\r\n");
      out.write("                      ♦ Dầu thực vật, dầu oliu, dầu cá,…<br>\r\n");
      out.write("                      ♦ Các loại rau: đa dạng các loại rau.<br>\r\n");
      out.write("                      ♦ Quả tươi: ăn đa dạng các loại quả\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td> ♦Mỡ động vật, phủ tạng động vật.<br>\r\n");
      out.write("                      ♦ Các thực phẩm chứa nhiều muối (đồ hộp, dưa muối, cà muối...).<br>\r\n");
      out.write("                      ♦ Các loại nước ngọt có ga, bánh kẹo ngọt.<br>\r\n");
      out.write("                      ♦ Các chất kích thích như: rượu, bia, cà phê, thuốc lá\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h5 id=\"qa5\" class=\"collapsed\" data-toggle=\"collapse\" data-target=\"#collapse5\" aria-expanded=\"false\" aria-controls=\"collapse5\">\r\n");
      out.write("              5. Lời khuyên cho 1 số đối tượng đặc biệt\r\n");
      out.write("            </h5>\r\n");
      out.write("            <div id=\"collapse5\" class=\"collapse\" aria-labelledby=\"qa5\" data-parent=\"#accordion\">\r\n");
      out.write("              <p>\r\n");
      out.write("                <strong>✤ Lời khuyên đối với người khuyết tật</strong><br>\r\n");
      out.write("                ✸ Người khuyết tật nhiễm COVID-19, ngoài việc cần chăm sóc như mọi người khác, thì cần được quan tâm,\r\n");
      out.write("                chăm sóc đặc biệt, nhất là với người có khó khăn trong tự phục vụ sinh hoạt hàng ngày...<br>\r\n");
      out.write("                ✸ Hãy mạnh mẽ và tự tin vào bản thân, chúng ta sẽ vượt qua đại dịch khi có kiến thức về phòng chống dịch\r\n");
      out.write("                COVID-19 và cách ly y tế, điều trị tại nhà.<br>\r\n");
      out.write("                ✸ Người khuyết tật có nguy cơ mắc bệnh COVID-19 với mức độ nặng cao hơn, vì vậy, người chăm sóc thường\r\n");
      out.write("                sẵn sàng các tình huống phải liên lạc với nhân viên y tế; theo dõi sát dấu hiệu của người nhiễm và cần\r\n");
      out.write("                chuyển cấp cứu kịp thời tại các cơ sở y tế điều trị COVID-19 trên địa bàn khi có các dấu hiệu cảnh báo\r\n");
      out.write("                khẩn cấp.<br>\r\n");
      out.write("                ✸ Kết hợp các hoạt động luyện tập phục hồi chức năng, tăng cường sức khỏe thể chất, tinh thần để giúp bù\r\n");
      out.write("                đắp cho việc hạn chế các hoạt động bên ngoài và tình trạng căng thẳng, lo lắng, trầm cảm, thất vọng.<br>\r\n");
      out.write("                ✸ Thường xuyên vệ sinh, khử khuẩn dụng cụ trợ giúp người khuyết tật trước và sau khi sử dụng.\r\n");
      out.write("                <br><br>\r\n");
      out.write("\r\n");
      out.write("                <strong>✤ Lời khuyên đối với người cao tuổi</strong><br>\r\n");
      out.write("                ✸ Người cao tuổi có nguy cơ mắc tình trạng nghiêm trọng khi mắc COVID-19 cao hơn các lứa tuổi khác. Tuổi\r\n");
      out.write("                càng cao, nguy cơ mắc bệnh mức độ nặng càng cao.<br>\r\n");
      out.write("                ✸ Người cao tuổi và người chăm sóc cần biết, theo dõi để phòng tránh nguy cơ diễn biến nặng và cần\r\n");
      out.write("                chuyển cấp cứu kịp thời tại bệnh viện trên địa bàn khi có các dấu hiệu cảnh báo khẩn cấp.<br>\r\n");
      out.write("                ✸ Thực hiện chế độ ăn đủ dinh dưỡng (1.700-1.900 Kcal/ngày), cân đối, lành mạnh, nhiều rau xanh. Đảm bảo\r\n");
      out.write("                ăn 3-4 bữa mỗi ngày, nếu ăn không đủ nên uống thêm các loại sữa bổ sung dinh dưỡng, từ 1-2 cốc mỗi\r\n");
      out.write("                ngày.<br>\r\n");
      out.write("                ✸ Cần thực hiện nghiêm ngặt chế độ dinh dưỡng bệnh lý và sử dụng thuốc đang điều trị bệnh sẵn có theo\r\n");
      out.write("                chỉ định của bác sĩ điều trị (không bỏ thuốc).<br>\r\n");
      out.write("                ✸ Tăng cường luyện tập tại phòng cách ly, trên giường tục theo điều kiện bằng các bài tập phục hồi chức\r\n");
      out.write("                năng, xoa bóp, hỗ trợ tập luyện để nâng cao sức khỏe.\r\n");
      out.write("                <br><br>\r\n");
      out.write("\r\n");
      out.write("                <strong>✤ Đối với trẻ em </strong><br>\r\n");
      out.write("                * Cha mẹ hãy bình tĩnh nếu con mình nhiễm COVID-19 và tự tin vào khả năng chăm sóc trẻ khi trẻ\r\n");
      out.write("                nhiễm.<br>\r\n");
      out.write("                ✸ Tâm sự, trấn an con về dịch COVID-19.<br>\r\n");
      out.write("                ✸ Giải đáp thắc mắc và chia sẻ thông tin thực tế về dịch COVID-19. Trẻ có thể hiểu sai thông tin và có\r\n");
      out.write("                thể hoảng sợ.<br>\r\n");
      out.write("                ✸ Hạn chế gia đình tiếp xúc và nói chuyện về tin tức, sự kiện về COVID-19 có thể gây hoang mang, sợ\r\n");
      out.write("                hãi.<br>\r\n");
      out.write("                ✸ Cố gắng duy trì những thói quen bình thường, sinh hoạt khoa học. Lập thời gian biểu cho các hoạt động\r\n");
      out.write("                học tập và nghỉ ngơi hoặc các hoạt động giải trí.<br>\r\n");
      out.write("                ✸ Hướng dẫn trẻ các hành động hàng ngày để giảm sự lây lan của mầm bệnh như: rửa tay thường xuyên; sử\r\n");
      out.write("                dụng khăn giấy hoặc khuỷu tay khi ho hoặc hắt hơi, sau đó vứt khăn giấy vào thùng đựng chất thải.<br>\r\n");
      out.write("                ✸ Tạo điều kiện cho trẻ tham gia các hoạt động giải trí trong phòng cách ly phù hợp như các trò chơi\r\n");
      out.write("                online hay cùng chơi với bố, mẹ…\r\n");
      out.write("                <br><br>\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section> \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write(" </body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Footer-->\r\n");
      out.write("<footer class=\"footer section section-sm\">\r\n");
      out.write("    <!-- Container Start -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-7 offset-md-1 offset-lg-0\">\r\n");
      out.write("                <!-- About -->\r\n");
      out.write("                <div class=\"block about\">\r\n");
      out.write("                    <!-- footer logo -->\r\n");
      out.write("                    <img src=\"images/footer.png\" alt=\"\" width=\"250\">\r\n");
      out.write("                    <!-- description -->\r\n");
      out.write("                    <p class=\"alt-color\">Cuộc sống bận rộn có thể khiến bạn quên đi sức khỏe bản thân,\r\n");
      out.write("                        đặc biệt là mùa covid. Nhưng đến khi bị bệnh, nhiều người lại không muốn đến bệnh viện\r\n");
      out.write("                        vì quá đông và nguy cơ lây nhiễm cao.\r\n");
      out.write("                        Hiểu được điều đó, COVID CARE có thể giúp bạn dễ dàng kết nối với\r\n");
      out.write("                        bác sĩ và tư vấn cũng như hướng dẫn trực tuyến tại nhà.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Link list -->\r\n");
      out.write("            <div class=\"col-lg-6 offset-lg-1 col-md-3\" style=\"text-align: right;\">\r\n");
      out.write("                <div class=\"block\">\r\n");
      out.write("                    <h4>Mọi đóng góp ý kiến xin liên hệ</h4>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">Đường dây nóng: 0123456789</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Email: group8@gmail.com</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Website: Covid Care</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Facebook: group8/facebook.com</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Container End -->\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- Footer Bottom -->\r\n");
      out.write("<footer class=\"footer-bottom\">\r\n");
      out.write("    <!-- Container Start -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <!-- Copyright -->\r\n");
      out.write("                <div class=\"copyright\">\r\n");
      out.write("                    <p style=\"text-align: center;\">Copyright © 2022</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /views/../common/nav.jsp(28,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.getUserType() == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    <li class=\"nav-item active\">\r\n");
          out.write("                                        <a class=\"nav-link\" href=\"management\">Quản lý</a>\r\n");
          out.write("                                    </li>\r\n");
          out.write("                                    <li class=\"nav-item active\">\r\n");
          out.write("                                        <a class=\"nav-link\" href=\"statistic\">Thống kê</a>\r\n");
          out.write("                                    </li>\r\n");
          out.write("                                    <li class=\"nav-item active\">\r\n");
          out.write("                                        <a class=\"nav-link\" href=\"news\">Tạo bản tin mới</a>\r\n");
          out.write("                                    </li>\r\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    ");
          if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /views/../common/nav.jsp(41,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.getUserType() == 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <li class=\"nav-item active\">\r\n");
          out.write("                                                <a class=\"nav-link\" href=\"timetable\">Lịch trình</a>\r\n");
          out.write("                                            </li>\r\n");
          out.write("                                            <li class=\"nav-item active\">\r\n");
          out.write("                                                <a class=\"nav-link\" href=\"patient\">Quản lý bệnh nhân</a>\r\n");
          out.write("                                            </li>\r\n");
          out.write("                                            <li class=\"nav-item active\">\r\n");
          out.write("                                                <a class=\"nav-link\" href=\"chat\">Hỗ Trợ Trực Tuyến</a>\r\n");
          out.write("                                            </li>\r\n");
          out.write("                                            <li class=\"nav-item active\">\r\n");
          out.write("                                                <a class=\"nav-link\" href=\"hospital\">Thông tin bệnh viện</a>\r\n");
          out.write("                                            </li>\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <li class=\"nav-item active\">\r\n");
          out.write("                                                <a class=\"nav-link\" href=\"chat\">Hỗ Trợ Trực Tuyến</a>\r\n");
          out.write("                                            </li>\r\n");
          out.write("                                            <li class=\"nav-item active\">\r\n");
          out.write("                                                <a class=\"nav-link\" href=\"news\">Tin tức</a>\r\n");
          out.write("                                            </li>\r\n");
          out.write("                                            <li class=\"nav-item active\">\r\n");
          out.write("                                                <a class=\"nav-link\" href=\"tutorial\">Hướng dẫn</a>\r\n");
          out.write("                                            </li>\r\n");
          out.write("                                            <li class=\"nav-item active\">\r\n");
          out.write("                                                <a class=\"nav-link\" href=\"timetable\">Thời gian biểu</a>\r\n");
          out.write("                                            </li>\r\n");
          out.write("                                            ");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f1);
      // /views/../common/nav.jsp(68,44) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.getUserType() == 3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                <li class=\"nav-item active\">\r\n");
          out.write("                                                    <a class=\"nav-link\" href=\"info\">Thông tin cá nhân</a>\r\n");
          out.write("                                                </li>\r\n");
          out.write("                                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent(null);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                ");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /views/../common/nav.jsp(80,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    <li class=\"nav-item\">                                   \r\n");
          out.write("                                        <a class=\"nav-link login-button\" href=\"login\">Đăng Nhập</a> \r\n");
          out.write("                                    </li>\r\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    <li class=\"nav-item\">\r\n");
          out.write("                                        <a class=\"nav-link login-button\" href=\"logout\">Đăng Xuất</a> \r\n");
          out.write("                                    </li>\r\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }
}
